# Build settings
markdown: kramdown
highlighter: rouge

# Site settings
title: "Research Blog"
description: > # this means to ignore newlines until "email:"
   My Digital Research Notebook

email: david.brough.0416@gmail.com
#blog logo
logo: "/research-blog/assets/images/logo_myrb.jpg"
# blog cover
cover: "/research-blog/assets/images/laptop.jpg"

name: 'David Brough'
author: 'David Brough'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "davidbrough1.github.io" # the base hostname & protocol for your site
# url: "http://localhost:4000"
baseurl: "/research-blog"

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/thedavidbrough
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/davidbrough1
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
  - icon: linkedin
    url:  https://www.linkedin.com/pub/david-brough/10/b01/243
    desc: Checkout my linkedin profile

gh:
  user: davidbrough1
  repo: research-blog
  # Branch hosting Github pages
  branch: gh-pages

disqus: davidbroughnet
