# Site settings
# Enter your own credentials here
title: "Research Blog"
email: david.brough.0416@gmail.com
description: > # Add blog description
  Research Blog
baseurl: "/research-blog" # replace ``/research-pages`` with the name of the parents repository
url: "davidbrough1.github.io" # replate ``Materials-Informatics-Lab`` with your Github username
twitter_username: thedavidbrough
disqus: davidbrough

# Build settings
markdown: kramdown

# Pagination of Posts efficiently organizes posts
# Using Pagination in Jekyll here: http://jekyllrb.com/docs/pagination/
paginate: 5


gh:
  user: davidbrough
  repo: research-notes
  # Branch hosting Github pages
  branch: gh-pages
